"use client";
import Footer from '@/AdminLayout/Footer/Footer';
import Header from '@/AdminLayout/Header/Header';
import Sidebar, { SidebarOverlay } from '@/AdminLayout/Sidebar/Sidebar';
import 'bootstrap/dist/css/bootstrap.min.css';
import Head from 'next/head';
import { useCallback, useEffect, useState } from 'react';
import { Container, Row, Col } from 'react-bootstrap';
import { useResizeDetector } from 'react-resize-detector';



export default function AdminLayout({ children }) {
    // Show status for xs screen
    const [isShowSidebar, setIsShowSidebar] = useState(false)
  
    // Show status for md screen and above
    const [isShowSidebarMd, setIsShowSidebarMd] = useState(true)
  
    const toggleIsShowSidebar = () => {
      setIsShowSidebar(!isShowSidebar)
    }
  
    const toggleIsShowSidebarMd = () => {
      const newValue = !isShowSidebarMd
      localStorage.setItem('isShowSidebarMd', newValue ? 'true' : 'false')
      setIsShowSidebarMd(newValue)
    }
  
    // Clear and reset sidebar
    const resetIsShowSidebar = () => {
      setIsShowSidebar(false)
    }
  
    const onResize = useCallback(() => {
      resetIsShowSidebar()
    }, [])
  
    const { ref } = useResizeDetector({ onResize })
  
    // On first time load only
    useEffect(() => {
      if (localStorage.getItem('isShowSidebarMd')) {
        setIsShowSidebarMd(localStorage.getItem('isShowSidebarMd') === 'true')
      }
    }, [setIsShowSidebarMd])
  
    return (
      <>
        <Head>
          <title>IDOL Mart Dashboard</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <div ref={ref} className="position-absolute w-100" />
  
        <Sidebar isShow={isShowSidebar} isShowMd={isShowSidebarMd} />
  
        <div className="wrapper d-flex flex-column min-vh-100 bg-light">
          <Header toggleSidebar={toggleIsShowSidebar} toggleSidebarMd={toggleIsShowSidebarMd} />
          <div className="body flex-grow-1 px-sm-2 mb-4">
            <Container fluid={true}>
              {children}
            </Container>
          </div>
          <Footer />
        </div>
  
        <SidebarOverlay isShowSidebar={isShowSidebar} toggleSidebar={toggleIsShowSidebar} />
      </>
    )
  }